
// This file has been generated by the GUI designer. Do not modify.
namespace Warcaby
{
	public partial class MainWindow
	{
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Image image2;
		
		private global::Gtk.Button button4;
		
		private global::Gtk.Button button5;
		
		private global::Gtk.Button button6;
		
		private global::Gtk.Button button7;
		
		private global::Gtk.Button button8;
		
		private global::Gtk.Button button9;
		
		private global::Gtk.Button button12;
		
		private global::Gtk.Button button11;
		
		private global::Gtk.Button button10;
		
		private global::Gtk.Button button13;
		
		private global::Gtk.Button button14;
		
		private global::Gtk.Button button15;
		
		private global::Gtk.Button button16;
		
		private global::Gtk.Button button18;
		
		private global::Gtk.Button button17;
		
		private global::Gtk.Button button20;
		
		private global::Gtk.Button button21;
		
		private global::Gtk.Button button19;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Button button2;
		
		private global::Gtk.Button button1;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.CheckButton checkbutton1;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Button button3;
		
		private global::Gtk.Button button22;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Warcaby.MainWindow
			this.Name = "Warcaby.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Warcaby");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Warcaby.ikona.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Warcaby.MainWindow.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.WidthRequest = 760;
			this.fixed1.HeightRequest = 600;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.image2 = new global::Gtk.Image ();
			this.image2.WidthRequest = 600;
			this.image2.HeightRequest = 600;
			this.image2.Name = "image2";
			this.image2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Warcaby.tlo.jpg");
			this.fixed1.Add (this.image2);
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button4 = new global::Gtk.Button ();
			this.button4.WidthRequest = 100;
			this.button4.HeightRequest = 100;
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.fixed1.Add (this.button4);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button4]));
			w2.X = 100;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button5 = new global::Gtk.Button ();
			this.button5.WidthRequest = 100;
			this.button5.HeightRequest = 100;
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.fixed1.Add (this.button5);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button5]));
			w3.X = 300;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button6 = new global::Gtk.Button ();
			this.button6.WidthRequest = 100;
			this.button6.HeightRequest = 100;
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			this.fixed1.Add (this.button6);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button6]));
			w4.X = 500;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button7 = new global::Gtk.Button ();
			this.button7.WidthRequest = 100;
			this.button7.HeightRequest = 100;
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			this.fixed1.Add (this.button7);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button7]));
			w5.Y = 100;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button8 = new global::Gtk.Button ();
			this.button8.WidthRequest = 100;
			this.button8.HeightRequest = 100;
			this.button8.CanFocus = true;
			this.button8.Name = "button8";
			this.button8.UseUnderline = true;
			this.fixed1.Add (this.button8);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button8]));
			w6.X = 200;
			w6.Y = 100;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button9 = new global::Gtk.Button ();
			this.button9.WidthRequest = 100;
			this.button9.HeightRequest = 100;
			this.button9.CanFocus = true;
			this.button9.Name = "button9";
			this.fixed1.Add (this.button9);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button9]));
			w7.X = 400;
			w7.Y = 100;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button12 = new global::Gtk.Button ();
			this.button12.WidthRequest = 100;
			this.button12.HeightRequest = 100;
			this.button12.CanFocus = true;
			this.button12.Name = "button12";
			this.button12.UseUnderline = true;
			this.fixed1.Add (this.button12);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button12]));
			w8.X = 500;
			w8.Y = 200;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button11 = new global::Gtk.Button ();
			this.button11.WidthRequest = 100;
			this.button11.HeightRequest = 100;
			this.button11.CanFocus = true;
			this.button11.Name = "button11";
			this.button11.UseUnderline = true;
			this.fixed1.Add (this.button11);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button11]));
			w9.X = 300;
			w9.Y = 200;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button10 = new global::Gtk.Button ();
			this.button10.WidthRequest = 100;
			this.button10.HeightRequest = 100;
			this.button10.CanFocus = true;
			this.button10.Name = "button10";
			this.button10.UseUnderline = true;
			this.fixed1.Add (this.button10);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button10]));
			w10.X = 100;
			w10.Y = 200;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button13 = new global::Gtk.Button ();
			this.button13.WidthRequest = 100;
			this.button13.HeightRequest = 100;
			this.button13.CanFocus = true;
			this.button13.Name = "button13";
			this.button13.UseUnderline = true;
			this.fixed1.Add (this.button13);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button13]));
			w11.Y = 300;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button14 = new global::Gtk.Button ();
			this.button14.WidthRequest = 100;
			this.button14.HeightRequest = 100;
			this.button14.CanFocus = true;
			this.button14.Name = "button14";
			this.button14.UseUnderline = true;
			this.fixed1.Add (this.button14);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button14]));
			w12.X = 200;
			w12.Y = 300;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button15 = new global::Gtk.Button ();
			this.button15.WidthRequest = 100;
			this.button15.HeightRequest = 100;
			this.button15.CanFocus = true;
			this.button15.Name = "button15";
			this.button15.UseUnderline = true;
			this.fixed1.Add (this.button15);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button15]));
			w13.X = 400;
			w13.Y = 300;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button16 = new global::Gtk.Button ();
			this.button16.WidthRequest = 100;
			this.button16.HeightRequest = 100;
			this.button16.CanFocus = true;
			this.button16.Name = "button16";
			this.button16.UseUnderline = true;
			this.fixed1.Add (this.button16);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button16]));
			w14.X = 100;
			w14.Y = 400;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button18 = new global::Gtk.Button ();
			this.button18.WidthRequest = 100;
			this.button18.HeightRequest = 100;
			this.button18.CanFocus = true;
			this.button18.Name = "button18";
			this.button18.UseUnderline = true;
			this.fixed1.Add (this.button18);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button18]));
			w15.X = 500;
			w15.Y = 400;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button17 = new global::Gtk.Button ();
			this.button17.WidthRequest = 100;
			this.button17.HeightRequest = 100;
			this.button17.CanFocus = true;
			this.button17.Name = "button17";
			this.button17.UseUnderline = true;
			this.fixed1.Add (this.button17);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button17]));
			w16.X = 300;
			w16.Y = 400;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button20 = new global::Gtk.Button ();
			this.button20.WidthRequest = 100;
			this.button20.HeightRequest = 100;
			this.button20.CanFocus = true;
			this.button20.Name = "button20";
			this.button20.UseUnderline = true;
			this.fixed1.Add (this.button20);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button20]));
			w17.X = 200;
			w17.Y = 500;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button21 = new global::Gtk.Button ();
			this.button21.WidthRequest = 100;
			this.button21.HeightRequest = 100;
			this.button21.CanFocus = true;
			this.button21.Name = "button21";
			this.button21.UseUnderline = true;
			this.fixed1.Add (this.button21);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button21]));
			w18.X = 400;
			w18.Y = 500;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button19 = new global::Gtk.Button ();
			this.button19.WidthRequest = 100;
			this.button19.HeightRequest = 100;
			this.button19.CanFocus = true;
			this.button19.Name = "button19";
			this.button19.UseUnderline = true;
			this.button19.Label = global::Mono.Unix.Catalog.GetString (" ");
			this.fixed1.Add (this.button19);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button19]));
			w19.Y = 500;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("⊕ - pion komputera");
			this.fixed1.Add (this.label1);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
			w20.X = 610;
			w20.Y = 100;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Ω - dama komputera");
			this.fixed1.Add (this.label2);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
			w21.X = 610;
			w21.Y = 130;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Θ - pion gracza");
			this.fixed1.Add (this.label3);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
			w22.X = 610;
			w22.Y = 10;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Ψ - dama gracza");
			this.fixed1.Add (this.label4);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
			w23.X = 610;
			w23.Y = 30;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button2 = new global::Gtk.Button ();
			this.button2.WidthRequest = 140;
			this.button2.HeightRequest = 30;
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString ("Wyłącz!");
			this.fixed1.Add (this.button2);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button2]));
			w24.X = 610;
			w24.Y = 560;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button1 = new global::Gtk.Button ();
			this.button1.WidthRequest = 140;
			this.button1.HeightRequest = 30;
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString ("Od Nowa!");
			this.fixed1.Add (this.button1);
			global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button1]));
			w25.X = 610;
			w25.Y = 525;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Gracz 1");
			this.fixed1.Add (this.label5);
			global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label5]));
			w26.X = 610;
			w26.Y = 200;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.checkbutton1 = new global::Gtk.CheckButton ();
			this.checkbutton1.CanFocus = true;
			this.checkbutton1.Name = "checkbutton1";
			this.checkbutton1.Label = global::Mono.Unix.Catalog.GetString ("Ustaw piony");
			this.checkbutton1.DrawIndicator = true;
			this.checkbutton1.UseUnderline = true;
			this.fixed1.Add (this.checkbutton1);
			global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.checkbutton1]));
			w27.X = 610;
			w27.Y = 420;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Z pola numer ");
			this.fixed1.Add (this.label6);
			global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label6]));
			w28.X = 610;
			w28.Y = 340;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Na pole numer ");
			this.fixed1.Add (this.label7);
			global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label7]));
			w29.X = 610;
			w29.Y = 360;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Podpowiedzi \ndla gracza 2:");
			this.fixed1.Add (this.label8);
			global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label8]));
			w30.X = 610;
			w30.Y = 300;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button3 = new global::Gtk.Button ();
			this.button3.WidthRequest = 140;
			this.button3.HeightRequest = 30;
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString ("Gracz vs Gracz");
			this.fixed1.Add (this.button3);
			global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button3]));
			w31.X = 610;
			w31.Y = 490;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button22 = new global::Gtk.Button ();
			this.button22.WidthRequest = 140;
			this.button22.HeightRequest = 30;
			this.button22.CanFocus = true;
			this.button22.Name = "button22";
			this.button22.UseUnderline = true;
			this.button22.Label = global::Mono.Unix.Catalog.GetString ("Gracz vs Komputer");
			this.fixed1.Add (this.button22);
			global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button22]));
			w32.X = 610;
			w32.Y = 455;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 760;
			this.DefaultHeight = 600;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.button2.Clicked += new global::System.EventHandler (this.OnButton2ClickEvent);
			this.button1.Clicked += new global::System.EventHandler (this.OnButton1ClickEvent);
			this.button3.Clicked += new global::System.EventHandler (this.przeciwGracz);
			this.button22.Clicked += new global::System.EventHandler (this.przeciwKomputer);
		}
	}
}
